#!/usr/local/bin/perl
# use unix or u a punkbich button-smash hack-of-a-hacker
#                               t(o0)j sk-a-dk-gui-scrub

use strict; use warnings;
use LWP::UserAgent;
use LWP::Protocol::https;

#########################################################
# INCREMENT - grab interesting htmls by ++

my ($path, $point, $max, $url) = @ARGV;
die "ARG1 path, ARG2 point, ARG3 max, ARG4 url" if (!defined $url); 

# PREP ##################################################
my $YAY = 0;



#########################################################
#########################################################


#########################################################
#########################################################

#########################################################
#########################################################
