#!/usr/local/bin/perl
# use unix or u a punkbich button-smash hack-of-a-hacker
#                               t(o0)j sk-a-dk-gui-scrub

use strict; use warnings;
use LWP::UserAgent;
use LWP::Protocol::https;

#########################################################
# INCREMENT - grab interesting htmls by ++

# PREP ##################################################
my ($path, $point, $max, $url) = @ARGV;
die "ARG1 path, ARG2 point, ARG3 max, ARG4 url" if (!defined $url);

my $YAY = 0;
my $FAIL = 0;

# WORK ##################################################
while ($point < $max)
{
  sleep 3;
  neo($point);
  $point++;
}
print "DONE $point";

# SUB ###################################################
sub uagent
{
  my $s_ua = LWP::UserAgent->new(
    agent => "Mozilla/50.0.2",
    from => "punxnotdead",
    timeout => 45,
  )
  return $s_ua;
}

sub neo
{
  my ($i) = @_;
  my $ua = uagent();
  my $url = $base.$i;
  my $file = "$path/$i";
  $ua->get($url, ':content_file'=>$file);
  if (-e $file)
    { $YAY++; print "YAY $i   ttl $YAY   $url\n"; }
  else
    { $FAIL++; print "FAIL $i   ttl $FAIL   $url\n";}
}
