#!/usr/local/bin/perl
# use unix or u a punkbich button-smash hack-of-a-hacker
#                               t(o0)j sk-a-dk-gui-scrub

use strict; use warnings;
use LWP::UserAgent;
use LWP::Protocol::https;
use File::Copy 'move';

#########################################################
# RIP_HTML - grab interesting urls from htmls

# PREP ##################################################

my ($dir, $head_regx, $tail_regx, $head_rm, $tail_rm) = @ARGV;
die "ARG1 html_dump_dir, ARG2 first_regx, ARG3 second_regx, ARG4 head, ARG5 tail" if (!defined $tail);

$dir =~ s%/\z%%;
my $got = $dir.'got/';
mkdir $got;

my $payload = $dir.GET;
open(my $Gfh, >>, $payload);

opendir(my $DH, $dir) or die "Bad dir $dir";
my @files = readdir($DH); chomp @files;

for (@files)
{
  my $i = $dir.$_;
  open(my $ifh, '<', $i);
  my @lines = <$ifh>; chomp @lines;
  my $yay = 0;

  for (@lines)
  {
    if (/$head_regx/ && /$tail_regx/)
    {
# all urls grabbed to a global file to send to HIVE
      my $url = $_;
      $url =~ s?.*$head??;
      $url =~ s?$tail.*??;
      print $Gfh "$url\n";
      $yay++;
    }
  }
# processed files go into got dir
# ONLY IF URLS WERE GRABBED
  my $new_html = $got.$_;
  print "$new_html\n";
  move($i, $new_html) if ($yay > 0);
}
